version: '3.5'

services:
  # database
  mariadb:
    image: 'bitnami/mariadb:10.3'
    ports:
      - '3306:3306'
    container_name: ${PROJECT_NAME}_mariadb
    volumes:
      - ${PROJECT_DIR}:/bitnami
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - MARIADB_ROOT_PASSWORD=bn_root
    networks:
      - bitnami_network
  # wordpress
  wordpress:
    image: 'bitnami/wordpress'
    ports:
      - '80:80'
      - '443:443'
    container_name: ${PROJECT_NAME}_wordpress
    volumes:
      - ${PROJECT_DIR}:/bitnami
      - ${PROJECT_DIR}/wordpress:/home/bitnami/apps/wordpress/htdocs/ # aws lightsail wordpress
    working_dir: /bitnami
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
    networks:
      - bitnami_network
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    container_name: ${PROJECT_NAME}_phpmyadmin
    environment:
      PMA_HOST: mariadb
    networks:
      - bitnami_network
  # wordmove
  wordmove:
    tty: true
    depends_on:
      - wordpress
    image: laittg/wordmove
    container_name: ${PROJECT_NAME}_wordmove
    volumes:
      - ${PROJECT_DIR}:/bitnami
      - ./.env:/home/wordmove/.env:ro
      - ./movefile.yml:/home/wordmove/movefile.yml:ro
      - ./wp-cli.yml:/home/wordmove/wp-cli.yml:ro
      - ~/${SSH_DIR}:/home/wordmove/${SSH_DIR}:ro
      - ~/${SSH_DIR}/id_rsa:/home/wordmove/.ssh/id_rsa:ro
      - ~/.ssh/config:/home/wordmove/.ssh/config:ro
      - ~/.ssh/known_hosts:/home/wordmove/.ssh/known_hosts
    networks:
      - bitnami_network

networks:
  bitnami_network:
    name: ${PROJECT_NAME}_default

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
