global:
  sql_adapter: wpcli

local:
  vhost: http://ecoparkmarathon.local
  wordpress_path: /bitnami # use an absolute path here

  database:
    name: bitnami_wordpress
    user: bn_wordpress
    password: "bn_wordpress" # could be blank, so always use quotes around
    host: mariadb

production:
  vhost: http://epm.ecobus.vn
  wordpress_path: /home/bitnami/apps/wordpress/htdocs # use an absolute path here

  database:
    name: bitnami_wordpress
    user: bn_wordmove
    password: "a8406704c1"
    host: "54.169.241.34"
    # port: 3308 # Use just in case you have exotic server config
    mysqldump_options: '--max_allowed_packet=1G' # Only available if using SSH
    mysql_options: '--protocol=TCP' # mysql command is used to import db

  exclude:
    - '.git/'
    - '.gitignore'
    - '.gitmodules'
    - '.env'
    - 'node_modules/'
    - 'bin/'
    - 'tmp/*'
    - 'Gemfile*'
    - 'Movefile'
    - 'movefile'
    - 'movefile.yml'
    - 'movefile.yaml'
    - 'wp-config.php'
    - 'wp-content/*.sql.gz'
    - '*.orig'

  # paths: # you can customize wordpress internal paths
  #   wp_content: wp-content
  #   uploads: wp-content/uploads
  #   plugins: wp-content/plugins
  #   mu_plugins: wp-content/mu-plugins
  #   themes: wp-content/themes
  #   languages: wp-content/languages

  ssh:
    host: "epm:wp"
    # user: bitnami
    # password: password # password is optional, will use public keys if available.
    # port: 22 # Port is optional
    rsync_options: '--verbose --itemize-changes' # Additional rsync options, optional
    # gateway: # Gateway is optional
    #   host: host
    #   user: user
    #   password: password # password is optional, will use public keys if available.

  # ftp:
  #   user: user
  #   password: password
  #   host: host
  #   passive: true
  #   port: 21 # Port is optional
  #   scheme: ftps # default `ftp`. alternative `sftp`

  # hooks: # Remote hooks won't work with FTP
  #   push:
  #     before:
  #       local:
  #         - 'echo "Do something locally before push"'
  #       remote:
  #         - 'echo "Do something remotely before push"'
  #     after:
  #       local:
  #         - 'echo "Do something locally after push"'
  #       remote:
  #         - 'echo "Do something remotely after push"'
  #   pull:
  #     before:
  #       local:
  #         - 'echo "Do something locally before pull"'
  #       remote:
  #         - 'echo "Do something remotely before pull"'
  #     after:
  #       local:
  #         - 'echo "Do something locally after pull"'
  #       remote:
  #         - 'echo "Do something remotely after pull"'
  # forbid:
  #   push:
  #     db: false
  #     plugins: false
  #     themes: false
  #     languages: false
  #     uploads: false
  #     mu-plugins: false
  #   pull:
  #     db: false
  #     plugins: false
  #     themes: false
  #     languages: false
  #     uploads: false
  #     mu-plugins: false

# staging: # multiple environments can be specified
#   [...]
